include $(GOROOT)/src/Make.$(GOARCH)

TARG=github.com/petar/GoNeedle/needle/proto
GOFILES=\
	needle.pb.go\

include $(GOROOT)/src/Make.pkg
include $(GOROOT)/src/pkg/goprotobuf.googlecode.com/hg/Make.protobuf
