include $(GOROOT)/src/Make.inc

TARG=github.com/petar/GoNeedle/needle
GOFILES=\
	dial.go\
	peer.go\
	server.go\
	signal.go\
	specs.go\
	#punch.go\
	#conn.go\
	#api.go\

include $(GOROOT)/src/Make.pkg
